AWSTemplateFormatVersion: 2010-09-09
Description: A cfn template to test out cfn-lint with precommit hook
# Metadata:

# Parameters:

# Mappings:

# Conditions:

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.16.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: cfn-lint-test-vpc
# Outputs:
